#!/bin/sh -e

HOST="${1:-plex-server}"
shift 2>/dev/null || true

echo "Applying NixOS configuration for ${HOST}..."
sudo SSH_AUTH_SOCK=$SSH_AUTH_SOCK /run/current-system/sw/bin/nixos-rebuild switch --flake ".#${HOST}" "$@"
echo "Switch to new generation complete!"
