name: Build hosts

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: Verify hosts build
        run: |
          set -e
          system=x86_64-linux
          hosts=$(nix eval --json --impure ".#checks.$system" --apply 'builtins.attrNames' | jq -r '.[]')
          for host in $hosts; do
            echo "::group::Verifying $host"
            nix build ".#checks.$system.$host" --dry-run --impure
            echo "::endgroup::"
          done
