name: Build hosts

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: Verify hosts build
        run: |
          set -e
          system=x86_64-linux
          hosts=$(nix eval --json --impure ".#checks.$system" --apply 'builtins.attrNames' | jq -r '.[]')
          for host in $hosts; do
            echo "::group::Verifying $host"
            nix build ".#checks.$system.$host" --dry-run --impure
            echo "::endgroup::"
          done
